swagger: '2.0'
info:
  title: TESTED<svg><!--?php "--><script>confirm(1)</script>?&gt;</svg>
  description: |
       <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert('sulistest')'>">
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        0: 
      operationId: findAccounts
      summary: [Client account information]
